name: Build and deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t stereo2025/inst_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run : echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push stereo2025/inst_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "deploy/docker-compose.yaml"
          target: "inst_app_ci"
          strip_components: 1
      - name: deploy add
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd inst_app_ci
            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d 
